### ISSUE TITLE
iOS Chore - CI Script

### ISSUE THREAD

**Issue by Vince-Ku** [No-57/SCSH_3C_iOS#15]
# Chore

Language: Ruby
Dependency Management: [Ruby Bundler](https://bundler.io/)
Library: [Fastlane](https://fastlane.tools/)

- [x] Establishment
   - [x]  new git repository or not
   - [x] guideline

- [x] Script
   - [x] git clone
   - [x] git checkout branch
   - [x] install third-party library
   - [x] match certificate in every target
   - [x] build code
   - [x] run all unit tests

**Comment by Vince-Ku** [comment]
I am still contemplating transferring CI to another Git repository...

**Comment by shadow3x3x3** [comment]
> I am still contemplating transferring CI to another Git repository...

IMHO, separating the CI into another repo feels a bit strange to me. The CI repo cannot run standalone eventually.

Do you have any reference example or blog?

**Comment by Vince-Ku** [comment]
> IMHO, separating the CI into another repo feels a bit strange to me. The CI repo cannot run standalone eventually.

can't agree more!! no wonder Fastlane requires an iOS project in the same directory when it's initialized.

> Do you have any reference example or blog?

My ex-company used to separate CI into the independent repo,  we change config by passing arguments in Jenkins.
In some level, It indeed enhances reusability but decreases flexibility. Perhaps putting it inside the same repo is a good practice to do.
