### ISSUE TITLE
iOS Chore - CI integrate into Github

### ISSUE THREAD

**Issue by Vince-Ku** [No-57/SCSH_3C_iOS#17]
# Chore

- [x] execute CI script when the pull request is changed ( including creating, committing, merging )
- [x] adjust CI script for this scenario
- [x] set up link rule in GitHub Setting (optional) 
  > no need, cause Kanban in GitHub is sufficient for issue tracking.

**Comment by shadow3x3x3** [comment]
Maybe reopen this issue and link to a new PR as well.

**Comment by Vince-Ku** [comment]
> Maybe reopen this issue and link to a new PR as well.

done

Why does it close automatically? 
I just mentioned it in the message of the previous PR...

**Comment by shadow3x3x3** [comment]
> Why does it close automatically? I just mentioned it in the message of the previous PR...

If you use [_**solved** .... #issue_](https://github.com/No-57/SCSH_3C_iOS/pull/16#issue-1902756871), it will be linked automatically.

Ref: [Linking a pull request to an issue using a keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)
