### ISSUE TITLE
iOS Feature - Persistence design

### ISSUE THREAD

**Issue by Vince-Ku** [No-57/SCSH_3C_iOS#43]
## Feature
Design the data structure in the `Persistence` module.

This is utilized for caching purposes, serving as SSOT in iOS.

---

### Board

```mermaid
erDiagram
    Board {
        int id "Unique identifier for the board (Primary Key, Auto-Increment)"
        string code "Code used to filter/query"        
        string image_url "URL of the board's image"
        string action_type "Type of the action, like Deep link, Universal link, Web link, Javascript execution... etc"
        string action "Action content" 
    }

```

#### Example Data:
    id: 1
    code: "product_side_bar"
    image_url: "http://example.com/image.jpg"
    action_type: "deep_link"
    action: "orange://main_page"
---

### Theme

```mermaid
erDiagram
    Theme {
        int id "Unique identifier for the theme (Primary Key, Auto-Increment)"
        string type "Type of the theme"
        string code "Code used to filter/query"
    }

```
#### Example Data:
    id: 1
    type: "Explore"
    code: "carousel_board"
---

### Distributor

```mermaid
erDiagram
    Distributor {
        int id "Unique identifier for the distributor (Primary Key, Auto-Increment)"
        string name "Name of the distributor"
        string description "Description of the distributor"
        string brand_image "URL to the brand's image"
        binary products "Distributor's Brand products"
    }

```
#### Example Data :
    id: 1
    name: "PCHome" 
    description : "台灣電商龍頭"
    brand_image : "http://example.com/image.jpg"
    products: [{"1", "http://example.com/image.jpg1"}, {"1", "http://example.com/image.jpg12"}]
---

### Distributor_Like

```mermaid
erDiagram
    Distributor_Like {
        int id "Unique identifier for the like (Primary Key, Auto-Increment)"
        int distributor_id "Identifier for the associated distributor"
    }

```

#### Example Data :
    id: 1
    distributor_id: 2 
---

#### APIs
[Board, Theme](https://github.com/No-57/SCSH_3C_iOS/issues/37)
[Distributor](https://github.com/No-57/SCSH_3C_iOS/issues/41)
[Product related](https://github.com/No-57/orange-frontstage-api/blob/main/API_design.md)

**Comment by Vince-Ku** [comment]
@shadow3x3x3 
This is a data structure I serving as SSOT in iOS, please take a look.

BTW, I also want to discuss the data structure for caching usage in Redis.

**Comment by shadow3x3x3** [comment]
It looks good, but you might need to modify it later based on No-57/orange-frontstage-api#18.

**Comment by Vince-Ku** [comment]
Updated !! 

BTW, I choose `Distributor_Like` in this scenario currently, because `Distributor` is the primary entity, and the `Like` is an action or attribute related to that Distributor.

But I am still hesitating about this design, cause it doesn't support user switching accounts.
